version: "3.8"

services:
  core-service:
    build:
      context: .
      dockerfile: Dockerfile.core
    expose:
      - "80"
    networks:
      - backend

  math-service:
    build:
      context: .
      dockerfile: Dockerfile.math
    expose:
      - "80"
    networks:
      - backend

  loadbalancer:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - core-service
      - math-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
